workflows:
  ios-build:
    name: iOS Build (Project)
    environment:
      vars:
        XCODE_PROJECT: "ios/skillovia.xcodeproj"
        XCODE_SCHEME: "skillovia"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS app
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build
    artifacts:
      - build/Build/Products/Release-iphoneos/*.app
      - build/Build/Products/Release-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
